Repository PyBotDevs/isobot, pull requests merged in 2022-05, with the labels that each got.

#29 fixed error log path
  utils/logger.py
Labels: bug, priority:high

#30 Fix single and plural "coin" and changed weird vocabulary
  main.py
Labels: priority:low, delay/to-do

#31 Add `hunt` command
  config/shop.json
  main.py
Labels: enhancement, currency framework update, priority:medium

#32 Make inventory fields inherit `inline=False`
  main.py
Labels: priority:low

#36 Changed shop desc because it was inaccurate
  main.py
Labels: debloat

#34 Add binoculars in shop config file
  config/shop.json
Labels: enhancement

#33 Add `fish` command
  config/shop.json
  main.py
Labels: enhancement, currency framework update

#41 Add basic implementation for `sell()`
  main.py
Labels: enhancement, currency framework update

#39 Create ideas.txt
  .dev/IDEAS.md
Labels: documentation

#42 Add hosting monitoring support
  .replit
  main.py
  utils/ping.py
Labels: enhancement, priority:high

#38 Add lootboxes in catalog
  config/data/lootbox.json
  config/shop.json
Labels: enhancement

#43 Create default database structure
  database/currency.json
  main.py
Labels: priority:critical

#44 Fix bug which allowed to sell more than a user had
  main.py
Labels: bug, currency framework update, priority:medium

#46 Make paths replit-compatible
  main.py
Labels: enhancement, priority:high

#47 Fix "item not found" error while selling items
  main.py
Labels: currency framework update, priority:high

#48 Add implementation for binoculars in `/scout`
  config/shop.json
  main.py
Labels: enhancement, currency framework update

#50 Add binoculars to `/inventory` command
  main.py
Labels: enhancement, currency framework update, priority:medium

#51 Add binoculars to `/shop` command catalog
  main.py
Labels: enhancement, currency framework update, priority:low

#53 Make dir creation system for logs
  main.py
  utils/logger.py
Labels: priority:low
