Repository PyBotDevs/isobot, pull requests merged in 2022-04, with the labels that each got.

#1 Remove positional argument in `warns_clear` command
  main.py
Labels: bug

#2 Fix warn success string
  main.py
Labels: bug

#3 Replace all mentions of `cash` and `crypto`
  main.py
Labels: currency framework update

#4 Add `deposit` command
  main.py
Labels: enhancement, currency framework update

#7 Add `daily`, `weekly` and `monthly` commands
  main.py
Labels: enhancement, currency framework update

#5 Add `withdraw` command
  main.py
Labels: enhancement, currency framework update

#6 Add `work` command
  main.py
Labels: enhancement, currency framework update

#8 Debloat a few imports
  main.py
Labels: debloat

#9 Add beg command
  main.py
Labels: enhancement, currency framework update

#10 Add `scout` command
  main.py
Labels: enhancement, currency framework update

#11 Updated to match rename
  README.md
Labels: documentation

#12 Patch `deposit` and `withdraw` commands
  main.py
Labels: bug

#13 Add `gift` command
  main.py
Labels: enhancement, currency framework update

#14 Patch all commands calling 'wallet'
  main.py
Labels: bug

#15 Add `rob` command
  main.py
Labels: enhancement, currency framework update

#16 Log stuff to console
  utils/logger.py
Labels: enhancement, priority:low

#19 Add base for `inventory` command
  database/items.json
  main.py
Labels: enhancement, currency framework update

#18 Add plugins config
  main.py
Labels: enhancement, priority:low

#20 Fix `warns_clear` command name
  main.py
Labels: bug

#21 Add `shop` command
  config/shop.json
  main.py
Labels: enhancement, currency framework update, priority:low

#22 Fix grammatical errors
  config/shop.json
  main.py
Labels: enhancement, debloat

#26 Complete `inventory` command and add Plugin-Check code for `buy` command
  main.py
Labels: enhancement, currency framework update

#27 Fix exception-handling builtins
  main.py
Labels: debloat, priority:ignored

#28 Fix slash command description grammar
  main.py
Labels: priority:low
